### ISSUE TITLE
Using a Ghost theme

### ISSUE THREAD

**Issue by MaluNoPeleke** [bnomei/kirby3-handlebars#16]
Would it be possible with this plugin to use a Ghost theme such as [Mapache](https://github.com/godofredoninja/Mapache) with Kirby?
If yes, what would be the required steps to make it work?

**Comment by bnomei** [comment]
oh thats an intersting question. but i guess not... lets sse why

- the repo has hbs files and hbs partials. that could be copied to kirbys template folder.
- ghost used handlebars js and my plugin a php port. so you will might have to reenable some features which the php lib does not by default. see [compiler flags](https://github.com/bnomei/kirby3-handlebars/blob/03c018f34e6202f289830bc95ad765af4d43aa99/index.php#L8)
- but the breaking issue will be the helpers that ghost registers to hbs which my plugin does not have and which are probably not shipped with the mapache theme either. stuff like this:

https://github.com/godofredoninja/Mapache/blob/495ce6a29f7cbe6cb0adf84443913a4920089566/godo-home-blog.hbs#L38
https://github.com/godofredoninja/Mapache/blob/495ce6a29f7cbe6cb0adf84443913a4920089566/custom-archive-tags.hbs#L10

**Comment by MaluNoPeleke** [comment]
Thanks a lot for the detailed answer, I already thought that it might not be that easy.
