### ISSUE TITLE
Custom variables in partials

### ISSUE THREAD

**Issue by dorb4n** [bnomei/kirby3-handlebars#17]
Hi.

Is it possible to pass custom variables to a partial, like:

`{{> @link url=navigation_url class=navigation_class}}`

`link` and `class` is in the link partial. When i try this, i get following error:

`Bnomei\LncFiles::precompiledTemplate(): Return value must be of type string, bool returned`

`navigation_class` and `navigation_url` are strings.

**Comment by bnomei** [comment]
you need to enable that feature in the compile flags.
https://github.com/bnomei/kirby3-handlebars/wiki/Handlebars:-Templates#settings

https://github.com/zordius/lightncandy#detail-feature-list
> {{>file foo bar=another}} : partial with new context which mixed with followed key value (require FLAG_RUNTIMEPARTIAL)

see defaults:
https://github.com/bnomei/kirby3-handlebars/blob/f1f45f627392a6d86792efc728652f21612bd9e5/index.php#L8



**site/config/config.php**
```php
<?php 

return [
     'bnomei.handlebarscompile-flags' => function () {
            // https://zordius.github.io/HandlebarsCookbook/9900-lc-options.html
            return \LightnCandy\LightnCandy::FLAG_ELSE
                | \LightnCandy\LightnCandy::FLAG_NOESCAPE
                // | \LightnCandy\LightnCandy::FLAG_PARENT
                | \LightnCandy\LightnCandy::FLAG_RUNTIMEPARTIAL // <-- uncommented from defaults
                // | \LightnCandy\LightnCandy::FLAG_NAMEDARG
                ;
        },
      // other options
];

**Comment by dorb4n** [comment]
Thank you :+1:  Works great.
